{
 "title": "Oracle Details GE4",
 "tags": [ "oracle" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ORADB", "query": "TMSAgent.%IBM.OracleAgentRDB" },
   { "name": "ORASERVERUNIX", "query": "TMSAgent.%IBM.STATIC013" }
  ]
 },
 "panels": [
  {
   "title": "ASM Disk % Usable",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "USEPET",
     "AttributeGroup": "MetricGroup.KRZASMDKGP",
     "Condition": "NAME='RECOC1'",
     "PrimaryKey": "NAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentASM",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "TOTAL_CNT",
     "AttributeGroup": "MetricGroup.KRZSESSSMY",
     "PrimaryKey": "DBINSTNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "TOTPROCESS",
     "AttributeGroup": "MetricGroup.KRZRDBPROS",
     "PrimaryKey": "DBINSTNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "ACTIVE_CNT",
     "AttributeGroup": "MetricGroup.KRZSESSSMY",
     "PrimaryKey": "DBINSTNAME",
     "alias": "Active Session Count",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "BACKGN_CNT",
     "AttributeGroup": "MetricGroup.KRZSESSSMY",
     "PrimaryKey": "DBINSTNAME",
     "alias": "Background Session Count",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "PINRATIO",
     "AttributeGroup": "MetricGroup.KRZLIBCART",
     "PrimaryKey": "INSTID",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "HITRATIO",
     "AttributeGroup": "MetricGroup.KRZBUFCART",
     "PrimaryKey": "DBINSTNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "PTOTLIMIT",
     "AttributeGroup": "MetricGroup.KRZRDBPROS",
     "PrimaryKey": "DBINSTNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "TTRANS",
     "AttributeGroup": "MetricGroup.KRZRDBRSS",
     "PrimaryKey": "INST_ID",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "LOCKCNT",
     "AttributeGroup": "MetricGroup.KRZRDBLS",
     "PrimaryKey": "LOCKTYPE",
     "alias": "Lock",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "FREEPCT",
     "AttributeGroup": "MetricGroup.KRZRDBDKSP",
     "Condition": "OWNER = 'audit_file_dest'",
     "PrimaryKey": "OWNER",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "type": "applications",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "TOTUPT",
     "AttributeGroup": "MetricGroup.KRZSGAOVEW",
     "PrimaryKey": "INSTID",
     "app_id": "asdas",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "type": "applications",
     "value": "MetricGroup.KLZTCP",
     "value1": "Select attribute",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "title": "Tablespace Free%",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "PCIFMAX",
     "AttributeGroup": "MetricGroup.KRZTSNLUE",
     "PrimaryKey": "TNAME",
     "alias": "T",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "WRITETIME",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "title": "%FREE TableSpace < 250GB",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "PCIFREE",
     "AttributeGroup": "MetricGroup.KRZTSNLUE",
     "Condition": "MBUSED < 250000",
     "PrimaryKey": "TNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "PCTUSED",
     "AttributeGroup": "MetricGroup.KRZRDBFRA",
     "PrimaryKey": "OWNER",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "type": "applications",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "TOTPGAUSMB",
     "AttributeGroup": "MetricGroup.KRZRDPGAOV",
     "PrimaryKey": "INSTID",
     "app_id": "asdas",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "type": "applications",
     "value": "MetricGroup.KLZTCP",
     "value1": "Select attribute",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "PTOTLIMIT",
     "AttributeGroup": "MetricGroup.KRZRDBPROS",
     "PrimaryKey": "DBINSTNAME",
     "alias": "Instance Name",
     "app_id": "asdas",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "type": "applications",
     "value": "MetricGroup.KLZTCP",
     "value1": "Select attribute",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "FREEPCT",
     "AttributeGroup": "MetricGroup.KRZRDBRFD",
     "PrimaryKey": "NAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "title": "DB Archive FS Used % Last12 hours",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent", "label": "PCT Used" }
   ],
   "targets": [
    {
     "AgentInstance": "$ORASERVERUNIX",
     "Attribute": "PCTSPCUSED",
     "AttributeGroup": "MetricGroup.UNIXDISK",
     "Condition": "UMOUNTPT contains 'arch'",
     "PrimaryKey": "UMOUNTPT",
     "alias": "USED%",
     "target": "TMSAgent.%IBM.STATIC013",
     "timeAttribute": "WRITETIME",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "title": "%FREE TableSpace > 250GB e < 1TB",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 21 },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "PCIFREE",
     "AttributeGroup": "MetricGroup.KRZTSNLUE",
     "Condition": "MBUSED >= 250000 and MBUSED < 1000000",
     "PrimaryKey": "TNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "title": "Total SGA (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "decmbytes", "label": "Number of Sessions" }
   ],
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "TTSGAMB",
     "AttributeGroup": "MetricGroup.KRZSGAOVEW",
     "PrimaryKey": "DBINSTNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "title": "Total PGA in use (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decmbytes", "label": "Number of Sessions" }
   ],
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "TOTPGAUSMB",
     "AttributeGroup": "MetricGroup.KRZRDPGAOV",
     "PrimaryKey": "DBINSTNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "title": "Table Sizes",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 30 },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "SIZEMB",
     "AttributeGroup": "MetricGroup.KRZDBTBSZ",
     "PrimaryKey": "TBNAME",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "WRITETIME",
     "timeRangeAttribute": "current",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "title": "%FREE TableSpace >1TB",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 30 },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "PCIFREE",
     "AttributeGroup": "MetricGroup.KRZTSNLUE",
     "Condition": "MBUSED >= 1000000",
     "PrimaryKey": "TNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "title": "Active Session Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Number of Sessions" }
   ],
   "targets": [
    {
     "AgentInstance": "$AgentName",
     "Attribute": "ACTIVE_CNT",
     "AttributeGroup": "MetricGroup.KRZSESSSMY",
     "PrimaryKey": "DBINSTNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "title": "Oracle Process Used % ",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "PTOTLIMIT",
     "AttributeGroup": "MetricGroup.KRZRDBPROS",
     "PrimaryKey": "DBINSTNAME",
     "alias": ".",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "TIMESTAMP",
     "timeRangeAttribute": "current",
     "valueAttribute": "value"
    }
   ]
  },
  {
   "title": "Lock Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "LOCKCNT",
     "AttributeGroup": "MetricGroup.KRZRDBLS",
     "PrimaryKey": "LOCKTYPE",
     "alias": "Lock",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "WRITETIME",
     "timeRangeAttribute": "dashboard",
     "valueAttribute": "displayValue"
    }
   ]
  },
  {
   "title": "Tables Number of Rows",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 39 },
   "targets": [
    {
     "AgentInstance": "$ORADB",
     "Attribute": "NUMROWS",
     "AttributeGroup": "MetricGroup.KRZDBTABLS",
     "PrimaryKey": "TBNAME",
     "alias": "TableName",
     "target": "TMSAgent.%IBM.OracleAgentRDB",
     "timeAttribute": "WRITETIME",
     "timeRangeAttribute": "current",
     "valueAttribute": "value"
    }
   ]
  }
 ]
}